### ISSUE TITLE
plz merge jan jonatan patch 1

### ISSUE THREAD

**Issue by TheJanJonatan** [PaulieGlot/lipu-sewi#15]
idk how to open a pull request on mobile but if you can do it without one please merge bc i put a correction

**Comment by PaulieGlot** [comment]
Have not re-merged old branch since it fell behind, instead just added name update to master branch.

**Comment by PaulieGlot** [comment]
Tried re-merging the patch branch, everything worked fine. In the future though please open new branches when performing updates
